'use strict';

/**
 * Reifegrad-Startbelegung aus dem Dokument „IT und OT Betrieb“
 * ==================================================================
 * Die Ampel-Bewertung (Text-Markierung grün/gelb/rot im Word-Dokument)
 * wurde je Maßnahme übernommen. Da die Bewertung im Dokument als eine
 * Gesamteinschätzung für den Geltungsbereich (DIHAG, EIS, DSO) vorliegt,
 * ist sie hier zunächst für alle drei Werke identisch vorbelegt und kann
 * je Werk verfeinert werden. Wird nur genutzt, solange noch keine
 * gespeicherte reifegrad-config.json existiert (initReifegrad).
 */

const REIFEGRAD_SEED = {
  meta: {
    quelle: 'IT und OT Betrieb.docx',
    hinweis: 'Aus dem Dokument übernommen (gilt für DIHAG, EIS, DSO); je Werk verfeinerbar.',
  },
  ratings: {
    R001: { DIHAG: 'rot', EIS: 'rot', DSO: 'rot' },
    R002: { DIHAG: 'rot', EIS: 'rot', DSO: 'rot' },
    R003: { DIHAG: 'gruen', EIS: 'gruen', DSO: 'gruen' },
    R004: { DIHAG: 'gelb', EIS: 'gelb', DSO: 'gelb' },
    R005: { DIHAG: 'rot', EIS: 'rot', DSO: 'rot' },
    R006: { DIHAG: 'rot', EIS: 'rot', DSO: 'rot' },
    R007: { DIHAG: 'gruen', EIS: 'gruen', DSO: 'gruen' },
    R008: { DIHAG: 'gelb', EIS: 'gelb', DSO: 'gelb' },
    R009: { DIHAG: 'gelb', EIS: 'gelb', DSO: 'gelb' },
    R010: { DIHAG: 'rot', EIS: 'rot', DSO: 'rot' },
    R011: { DIHAG: 'gelb', EIS: 'gelb', DSO: 'gelb' },
    R012: { DIHAG: 'rot', EIS: 'rot', DSO: 'rot' },
    R014: { DIHAG: 'gruen', EIS: 'gruen', DSO: 'gruen' },
    R015: { DIHAG: 'gelb', EIS: 'gelb', DSO: 'gelb' },
    R016: { DIHAG: 'gelb', EIS: 'gelb', DSO: 'gelb' },
    R017: { DIHAG: 'gruen', EIS: 'gruen', DSO: 'gruen' },
    R018: { DIHAG: 'gelb', EIS: 'gelb', DSO: 'gelb' },
    R019: { DIHAG: 'gruen', EIS: 'gruen', DSO: 'gruen' },
    R020: { DIHAG: 'gruen', EIS: 'gruen', DSO: 'gruen' },
    R021: { DIHAG: 'gruen', EIS: 'gruen', DSO: 'gruen' },
    R022: { DIHAG: 'gruen', EIS: 'gruen', DSO: 'gruen' },
    R024: { DIHAG: 'gruen', EIS: 'gruen', DSO: 'gruen' },
    R025: { DIHAG: 'gruen', EIS: 'gruen', DSO: 'gruen' },
    R026: { DIHAG: 'gelb', EIS: 'gelb', DSO: 'gelb' },
    R027: { DIHAG: 'gruen', EIS: 'gruen', DSO: 'gruen' },
    R028: { DIHAG: 'gruen', EIS: 'gruen', DSO: 'gruen' },
    R029: { DIHAG: 'gelb', EIS: 'gelb', DSO: 'gelb' },
    R030: { DIHAG: 'gelb', EIS: 'gelb', DSO: 'gelb' },
    R031: { DIHAG: 'gelb', EIS: 'gelb', DSO: 'gelb' },
    R032: { DIHAG: 'gelb', EIS: 'gelb', DSO: 'gelb' },
    R033: { DIHAG: 'gelb', EIS: 'gelb', DSO: 'gelb' },
    R034: { DIHAG: 'gelb', EIS: 'gelb', DSO: 'gelb' },
    R035: { DIHAG: 'gelb', EIS: 'gelb', DSO: 'gelb' },
    R036: { DIHAG: 'rot', EIS: 'rot', DSO: 'rot' },
    R037: { DIHAG: 'gruen', EIS: 'gruen', DSO: 'gruen' },
    R038: { DIHAG: 'gruen', EIS: 'gruen', DSO: 'gruen' },
    R039: { DIHAG: 'gelb', EIS: 'gelb', DSO: 'gelb' },
    R040: { DIHAG: 'gelb', EIS: 'gelb', DSO: 'gelb' },
    R041: { DIHAG: 'gelb', EIS: 'gelb', DSO: 'gelb' },
    R042: { DIHAG: 'gelb', EIS: 'gelb', DSO: 'gelb' },
    R043: { DIHAG: 'gelb', EIS: 'gelb', DSO: 'gelb' },
    R044: { DIHAG: 'rot', EIS: 'rot', DSO: 'rot' },
    R045: { DIHAG: 'gelb', EIS: 'gelb', DSO: 'gelb' },
    R046: { DIHAG: 'gelb', EIS: 'gelb', DSO: 'gelb' },
    R047: { DIHAG: 'gelb', EIS: 'gelb', DSO: 'gelb' },
    R048: { DIHAG: 'gelb', EIS: 'gelb', DSO: 'gelb' },
    R049: { DIHAG: 'gruen', EIS: 'gruen', DSO: 'gruen' },
    R050: { DIHAG: 'gelb', EIS: 'gelb', DSO: 'gelb' },
    R051: { DIHAG: 'rot', EIS: 'rot', DSO: 'rot' },
    R052: { DIHAG: 'rot', EIS: 'rot', DSO: 'rot' },
    R053: { DIHAG: 'gelb', EIS: 'gelb', DSO: 'gelb' },
    R055: { DIHAG: 'gruen', EIS: 'gruen', DSO: 'gruen' },
    R056: { DIHAG: 'gruen', EIS: 'gruen', DSO: 'gruen' },
    R057: { DIHAG: 'gruen', EIS: 'gruen', DSO: 'gruen' },
    R058: { DIHAG: 'gruen', EIS: 'gruen', DSO: 'gruen' },
    R059: { DIHAG: 'gelb', EIS: 'gelb', DSO: 'gelb' },
    R060: { DIHAG: 'rot', EIS: 'rot', DSO: 'rot' },
    R061: { DIHAG: 'gelb', EIS: 'gelb', DSO: 'gelb' },
    R062: { DIHAG: 'gelb', EIS: 'gelb', DSO: 'gelb' },
    R063: { DIHAG: 'gelb', EIS: 'gelb', DSO: 'gelb' },
    R064: { DIHAG: 'gelb', EIS: 'gelb', DSO: 'gelb' },
    R065: { DIHAG: 'gelb', EIS: 'gelb', DSO: 'gelb' },
    R066: { DIHAG: 'gruen', EIS: 'gruen', DSO: 'gruen' },
    R067: { DIHAG: 'gruen', EIS: 'gruen', DSO: 'gruen' },
    R068: { DIHAG: 'gelb', EIS: 'gelb', DSO: 'gelb' },
    R069: { DIHAG: 'gelb', EIS: 'gelb', DSO: 'gelb' },
    R070: { DIHAG: 'rot', EIS: 'rot', DSO: 'rot' },
    R071: { DIHAG: 'rot', EIS: 'rot', DSO: 'rot' },
    R072: { DIHAG: 'rot', EIS: 'rot', DSO: 'rot' },
    R073: { DIHAG: 'rot', EIS: 'rot', DSO: 'rot' },
    R074: { DIHAG: 'rot', EIS: 'rot', DSO: 'rot' },
    R075: { DIHAG: 'rot', EIS: 'rot', DSO: 'rot' },
    R076: { DIHAG: 'rot', EIS: 'rot', DSO: 'rot' },
    R077: { DIHAG: 'rot', EIS: 'rot', DSO: 'rot' },
    R078: { DIHAG: 'rot', EIS: 'rot', DSO: 'rot' },
    R079: { DIHAG: 'rot', EIS: 'rot', DSO: 'rot' },
    R080: { DIHAG: 'rot', EIS: 'rot', DSO: 'rot' },
    R081: { DIHAG: 'rot', EIS: 'rot', DSO: 'rot' },
    R082: { DIHAG: 'rot', EIS: 'rot', DSO: 'rot' },
    R083: { DIHAG: 'rot', EIS: 'rot', DSO: 'rot' },
    R084: { DIHAG: 'rot', EIS: 'rot', DSO: 'rot' },
    R085: { DIHAG: 'gelb', EIS: 'gelb', DSO: 'gelb' },
    R086: { DIHAG: 'gelb', EIS: 'gelb', DSO: 'gelb' },
    R087: { DIHAG: 'gruen', EIS: 'gruen', DSO: 'gruen' },
    R088: { DIHAG: 'rot', EIS: 'rot', DSO: 'rot' },
    R089: { DIHAG: 'gruen', EIS: 'gruen', DSO: 'gruen' },
    R090: { DIHAG: 'gelb', EIS: 'gelb', DSO: 'gelb' },
    R091: { DIHAG: 'rot', EIS: 'rot', DSO: 'rot' },
    R092: { DIHAG: 'rot', EIS: 'rot', DSO: 'rot' },
    R093: { DIHAG: 'rot', EIS: 'rot', DSO: 'rot' },
    R094: { DIHAG: 'rot', EIS: 'rot', DSO: 'rot' },
    R095: { DIHAG: 'rot', EIS: 'rot', DSO: 'rot' },
    R096: { DIHAG: 'gelb', EIS: 'gelb', DSO: 'gelb' },
    R097: { DIHAG: 'gelb', EIS: 'gelb', DSO: 'gelb' },
    R098: { DIHAG: 'gelb', EIS: 'gelb', DSO: 'gelb' },
    R099: { DIHAG: 'gruen', EIS: 'gruen', DSO: 'gruen' },
    R100: { DIHAG: 'gelb', EIS: 'gelb', DSO: 'gelb' },
    R101: { DIHAG: 'gelb', EIS: 'gelb', DSO: 'gelb' },
    R102: { DIHAG: 'gelb', EIS: 'gelb', DSO: 'gelb' },
    R103: { DIHAG: 'gelb', EIS: 'gelb', DSO: 'gelb' },
    R104: { DIHAG: 'rot', EIS: 'rot', DSO: 'rot' },
    R105: { DIHAG: 'gelb', EIS: 'gelb', DSO: 'gelb' },
    R106: { DIHAG: 'gelb', EIS: 'gelb', DSO: 'gelb' },
    R107: { DIHAG: 'rot', EIS: 'rot', DSO: 'rot' },
    R108: { DIHAG: 'rot', EIS: 'rot', DSO: 'rot' },
    R109: { DIHAG: 'rot', EIS: 'rot', DSO: 'rot' },
    R110: { DIHAG: 'gelb', EIS: 'gelb', DSO: 'gelb' },
    R111: { DIHAG: 'gelb', EIS: 'gelb', DSO: 'gelb' },
    R112: { DIHAG: 'gelb', EIS: 'gelb', DSO: 'gelb' },
    R113: { DIHAG: 'gelb', EIS: 'gelb', DSO: 'gelb' },
    R114: { DIHAG: 'gruen', EIS: 'gruen', DSO: 'gruen' },
    R115: { DIHAG: 'gruen', EIS: 'gruen', DSO: 'gruen' },
    R116: { DIHAG: 'gruen', EIS: 'gruen', DSO: 'gruen' },
    R117: { DIHAG: 'gruen', EIS: 'gruen', DSO: 'gruen' },
    R118: { DIHAG: 'gruen', EIS: 'gruen', DSO: 'gruen' },
    R119: { DIHAG: 'gruen', EIS: 'gruen', DSO: 'gruen' },
    R120: { DIHAG: 'gruen', EIS: 'gruen', DSO: 'gruen' },
    R122: { DIHAG: 'gruen', EIS: 'gruen', DSO: 'gruen' },
    R123: { DIHAG: 'gruen', EIS: 'gruen', DSO: 'gruen' },
    R124: { DIHAG: 'gruen', EIS: 'gruen', DSO: 'gruen' },
    R125: { DIHAG: 'gruen', EIS: 'gruen', DSO: 'gruen' },
    R126: { DIHAG: 'gelb', EIS: 'gelb', DSO: 'gelb' },
    R127: { DIHAG: 'gelb', EIS: 'gelb', DSO: 'gelb' },
    R128: { DIHAG: 'gelb', EIS: 'gelb', DSO: 'gelb' },
    R129: { DIHAG: 'gelb', EIS: 'gelb', DSO: 'gelb' },
    R130: { DIHAG: 'gelb', EIS: 'gelb', DSO: 'gelb' },
    R131: { DIHAG: 'gelb', EIS: 'gelb', DSO: 'gelb' },
  },
};
